
export const AppTheme = {
  colorPrimary: '#1A2D4E',
  backgroundGradientHome: [
    '#FAEFED',
    '#FAEFED',
    '#FAEFED',
    '#FAEFED',
    '#FAEFED',
    '#f2deda',
    '#f2deda',
    '#e3c0ba',
    '#e3c0ba',
  ],
  alarmCardColors: [
    '#f2e0dc',
    '#f2e0dc',
    '#f2e0dc',
    '#f2e0dc',
    '#f2e0dc',
    '#f0d5d1',
    '#f0d5d1',
    '#f0d5d1',
    '#f0d5d1',
    '#f0d5d1',
    '#e6c8c3',
    '#e6c8c3',
    '#e6c8c3',
    '#e6c8c3',
    '#e8c6c1',
    '#e8c6c1',
    '#ebc9c3',
    '#ebc9c3',
  ],
  buttonTextSetAlarm: 'white',
  buttonBackgroundSetAlarm: '#937EE9',
  buttonBackgroundPressedSetAlarm: '#a694f2',
  buttonBackgroundDisabledSetAlarm: '#1A2D4E',
};
